# db conn

# 配置数据库URI，格式为：postgresql://<username>:<password>@<hostname>/<database_name>
# db_connect: "postgresql://postgres:test@localhost/bf?client_encoding=utf8&timezone=utc"
# db_connect: "postgresql://postgres:admin@localhost/BlueFlame?client_encoding=utf8"

db_driver: "postgresql"
db_user: "postgres"
db_password: "test"
db_host: "localhost"
db_port: 5432
db_name: "bf"

# # 配置数据库连接池
# pool_size: 10
# max_overflow: 20
# pool_recycle: 300

# # 配置日志级别
# log_level: info

# # 配置日志文件路径
# log_file: /var/log/flame/flame.log

# # 配置日志格式
# log_format: '%(asctime)s - %(levelname)s - %(message)s'
