# db conn

# # 配置数据库连接池
# pool_size: 10
# max_overflow: 20
# pool_recycle: 300

# # 配置日志级别
# log_level: info

# # 配置日志文件路径
# log_file: /var/log/flame/flame.log

# # 配置日志格式
# log_format: '%(asctime)s - %(levelname)s - %(message)s'
