# db conn

# 配置数据库URI，格式为：postgresql://<username>:<password>@<hostname>/<database_name>
# db_connect: "postgresql://postgres:test@localhost/bf?client_encoding=utf8"
db_connect: "postgresql://postgres:admin@localhost/BlueFlame?client_encoding=utf8"
